import {useEffect,useState} from 'react';
type Row={xg_games:number;xgf:number|null;xga:number|null;xgd:number|null;xgf_avg:number|null;xga_avg:number|null;xgd_avg:number|null;id:number;rank:number;name:string;promoted:boolean;played:number;wins:number;draws:number;losses:number;gf:number;ga:number;points:number;ppg:number|null;clean:number;clean_pct:number|null;margins:number[];cover_pct:number|null};
export default function FormLabTable({league,home,away,domestic}:{league:string;home:string;away:string;domestic:boolean}){
 const [view,setView]=useState('form'),[venue,setVenue]=useState('all'),[window,setWindow]=useState('10'),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 useEffect(()=>{setView('form')},[league]);
 const [sort,setSort]=useState<{column:string;ascending:boolean}>({column:'Rank',ascending:true});
 useEffect(()=>{setSort({column:'Rank',ascending:true})},[view]);
 const value=(r:Row,column:string):number|string|null=>{
  const margins:Record<string,number>={'W1':0,'W2':1,'W3+':2,'L1':3,'L2':4,'L3+':5};
  if(column in margins)return r.margins[margins[column]];
  const fields:Record<string,number|string|null>={'xG games':r.xg_games,'npxG':r.xgf,'npxGA':r.xga,'npxGD':r.xgd,'npxG/game':r.xgf_avg,'npxGA/game':r.xga_avg,'npxGD/game':r.xgd_avg,Rank:r.rank,Team:r.name,P:r.played,W:r.wins,D:r.draws,L:r.losses,GF:r.gf,GA:r.ga,Pts:r.points,PPG:r.ppg,'Clean sheets':r.clean,'CS %':r.clean_pct,'−1.5 cover %':r.cover_pct};
  return fields[column]??null;
 };
 const sorted=[...rows].sort((a,b)=>{
  const sample=Number((view==='xg'?a.xg_games:a.played)<Number(window))-Number((view==='xg'?b.xg_games:b.played)<Number(window));if(sample)return sample;
  const av=value(a,sort.column),bv=value(b,sort.column);
  if(av===null||bv===null)return av===bv?a.rank-b.rank:av===null?1:-1;
  const delta=typeof av==='string'&&typeof bv==='string'?av.localeCompare(bv):Number(av)-Number(bv);
  return (sort.ascending?delta:-delta)||a.rank-b.rank;
 });

 useEffect(()=>{const c=new AbortController();setRows([]);setBusy(true);setError(false);if(!domestic&&['top6','tophalf','bottomhalf','bottom6'].includes(view)){setView('form');return()=>c.abort()}
 fetch('/api/form-lab/table?'+new URLSearchParams({league,view,venue,window}),{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setRows(d.teams)).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[league,view,venue,window,domestic]);
 return <section className="fl-panel" style={{marginBottom:22}}><h2>League form table</h2><div className="fl-grid three"><label>Table view<select value={view} onChange={e=>setView(e.target.value)}><option value="form">League form</option>{domestic&&<><option value="top6">Against top six</option><option value="tophalf">Against top half</option><option value="bottomhalf">Against bottom half</option><option value="bottom6">Against bottom six</option></>}<option value="handicap">Handicap margins</option><option value="clean">Clean sheets</option><option value="xg">Expected goals</option></select></label><div className="fl-compact"><span>Last</span><div className="fl-tabs">{[5,10,20].map(n=><button key={n} aria-pressed={window===String(n)} onClick={()=>setWindow(String(n))}>{n}</button>)}</div></div><div className="fl-tabs" aria-label="Form table venue">{['all','home','away'].map(v=><button key={v} aria-pressed={venue===v} onClick={()=>setVenue(v)}>{v}</button>)}</div></div>
 <details className="fl-options"><summary>How to read this table</summary><p className="fl-note">Each club's last {window} matching games, across available seasons. Cyan = selected home team; amber = selected away team. {view==='xg'?'Ranked by non-penalty xG difference per game. Only games with both xG values count; incomplete xG samples appear below full samples.':view==='handicap'?'Ranked by the percentage of wins by 2+ goals (covering −1.5).':view==='clean'?'Ranked by clean-sheet percentage.':'Ranked by points per game.'} Teams with fewer than {window} matching games are listed below teams with a full sample, even when sorting columns. Click a heading to reverse its sort order. Rank retains the original table ranking. * Promoted this season: only current-season matches are used, even when a larger sample is selected.</p></details>
 {busy&&<p role="status">Loading form table...</p>}{error&&<p role="alert">Could not load the table. Try another filter.</p>}
 <div className="fl-table-wrap"><table><thead><tr>{['Rank','Team','P',...(view==='xg'?['xG games','npxG','npxGA','npxGD','npxG/game','npxGA/game','npxGD/game']:view==='handicap'?['W1','W2','W3+','D','L1','L2','L3+','−1.5 cover %']:view==='clean'?['Clean sheets','CS %','GF','GA']:['W','D','L','GF','GA','Pts','PPG'])].map(c=><th key={c} aria-sort={sort.column===c?(sort.ascending?'ascending':'descending'):'none'}><button className="fl-sort" onClick={()=>setSort(s=>({column:c,ascending:s.column===c?!s.ascending:c==='Team'||c==='Rank'}))}>{c} <span aria-hidden="true">{sort.column===c?(sort.ascending?'↑':'↓'):'↕'}</span></button></th>)}</tr></thead><tbody>{sorted.map(r=><tr key={r.id} className={String(r.id)===home?'fl-home-row':String(r.id)===away?'fl-away-row':''}><td>{r.rank}</td><td>{r.name}{r.promoted&&<span>* (promoted)</span>}</td><td>{r.played}</td>{view==='xg'?<><td>{r.xg_games}/{r.played}</td>{[r.xgf,r.xga,r.xgd,r.xgf_avg,r.xga_avg,r.xgd_avg].map((v,i)=><td key={i}>{v===null?'—':v.toFixed(2)}</td>)}</>:view==='handicap'?<>{r.margins.slice(0,3).map((v,i)=><td key={i}>{v}</td>)}<td>{r.draws}</td>{r.margins.slice(3).map((v,i)=><td key={i}>{v}</td>)}<td>{r.cover_pct===null?'—':r.cover_pct.toFixed(0)+'%'}</td></>:view==='clean'?<><td>{r.clean}</td><td>{r.clean_pct===null?'—':r.clean_pct.toFixed(0)+'%'}</td><td>{r.gf}</td><td>{r.ga}</td></>:<><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.points}</td><td>{r.ppg===null?'—':r.ppg.toFixed(2)}</td></>}</tr>)}</tbody></table></div>
 {view==='xg'&&<p className="fl-note">Sportmonks non-penalty xG · Totals and averages use only the covered games within the selected sample. Missing xG is excluded, never zero.</p>}
 {view==='handicap'&&<p className="fl-note">W1/W2/W3+: won by exactly 1, exactly 2, or at least 3 goals. L columns show losing margins. Score-based outcomes, not betting returns.</p>}</section>
}
