import {useEffect,useState} from 'react';
type Row={id:number;rank:number;name:string;promoted:boolean;played:number;wins:number;draws:number;losses:number;gf:number;ga:number;points:number;ppg:number|null;clean:number;clean_pct:number|null;margins:number[];cover_pct:number|null};
export default function FormLabTable({league,home,away,domestic}:{league:string;home:string;away:string;domestic:boolean}){
 const [view,setView]=useState('form'),[venue,setVenue]=useState('all'),[window,setWindow]=useState('10'),[rows,setRows]=useState<Row[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(false);
 useEffect(()=>{setView('form')},[league]);
 useEffect(()=>{const c=new AbortController();setRows([]);setBusy(true);setError(false);if(!domestic&&['top6','tophalf','bottomhalf','bottom6'].includes(view)){setView('form');return()=>c.abort()}
 fetch('/api/form-lab/table?'+new URLSearchParams({league,view,venue,window}),{signal:c.signal}).then(r=>{if(!r.ok)throw Error();return r.json()}).then(d=>setRows(d.teams)).catch(e=>{if(e.name!=='AbortError')setError(true)}).finally(()=>{if(!c.signal.aborted)setBusy(false)});return()=>c.abort()},[league,view,venue,window,domestic]);
 return <section className="fl-panel" style={{marginBottom:22}}><h2>League form table</h2><div className="fl-grid three"><label>Table view<select value={view} onChange={e=>setView(e.target.value)}><option value="form">League form</option>{domestic&&<><option value="top6">Against top six</option><option value="tophalf">Against top half</option><option value="bottomhalf">Against bottom half</option><option value="bottom6">Against bottom six</option></>}<option value="handicap">Handicap margins</option><option value="clean">Clean sheets</option></select></label><div className="fl-compact"><span>Last</span><div className="fl-tabs">{[5,10,20].map(n=><button key={n} aria-pressed={window===String(n)} onClick={()=>setWindow(String(n))}>{n}</button>)}</div></div><div className="fl-tabs" aria-label="Form table venue">{['all','home','away'].map(v=><button key={v} aria-pressed={venue===v} onClick={()=>setVenue(v)}>{v}</button>)}</div></div>
 <details className="fl-options"><summary>How to read this table</summary><p className="fl-note">Each club's last {window} matching games, across available seasons. Cyan = selected home team; amber = selected away team. {view==='handicap'?'Ranked by the percentage of wins by 2+ goals (covering −1.5).':view==='clean'?'Ranked by clean-sheet percentage.':'Ranked by points per game.'} * Promoted this season; opponent-strength estimate is provisional while top-flight history builds.</p></details>
 {busy&&<p role="status">Loading form table...</p>}{error&&<p role="alert">Could not load the table. Try another filter.</p>}
 <div className="fl-table-wrap"><table><thead><tr>{['Rank','Team','P',...(view==='handicap'?['W1','W2','W3+','D','L1','L2','L3+','−1.5 cover %']:view==='clean'?['Clean sheets','CS %','GF','GA']:['W','D','L','GF','GA','Pts','PPG'])].map(c=><th key={c}>{c}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className={String(r.id)===home?'fl-home-row':String(r.id)===away?'fl-away-row':''}><td>{r.rank}</td><td>{r.name}{r.promoted&&<span>* (promoted)</span>}</td><td>{r.played}</td>{view==='handicap'?<>{r.margins.slice(0,3).map((v,i)=><td key={i}>{v}</td>)}<td>{r.draws}</td>{r.margins.slice(3).map((v,i)=><td key={i}>{v}</td>)}<td>{r.cover_pct===null?'—':r.cover_pct.toFixed(0)+'%'}</td></>:view==='clean'?<><td>{r.clean}</td><td>{r.clean_pct===null?'—':r.clean_pct.toFixed(0)+'%'}</td><td>{r.gf}</td><td>{r.ga}</td></>:<><td>{r.wins}</td><td>{r.draws}</td><td>{r.losses}</td><td>{r.gf}</td><td>{r.ga}</td><td>{r.points}</td><td>{r.ppg===null?'—':r.ppg.toFixed(2)}</td></>}</tr>)}</tbody></table></div>
 {view==='handicap'&&<p className="fl-note">W1/W2/W3+: won by exactly 1, exactly 2, or at least 3 goals. L columns show losing margins. Score-based outcomes, not betting returns.</p>}</section>
}
