"""add_user_subscription_magic_link_tables

Revision ID: f3c87bb06c45
Revises: 003
Create Date: 2026-03-13 14:18:09.412830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3c87bb06c45'
down_revision: Union[str, None] = '003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('email_subscribers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_subscribers_email'), 'email_subscribers', ['email'], unique=True)
    op.create_table('magic_links',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_links_email'), 'magic_links', ['email'], unique=False)
    op.create_index(op.f('ix_magic_links_token'), 'magic_links', ['token'], unique=True)
    op.create_table('syndicate_alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('market', sa.String(length=20), nullable=False),
    sa.Column('outcome', sa.String(length=20), nullable=False),
    sa.Column('movement_percent', sa.Float(), nullable=False),
    sa.Column('odds_at_alert', sa.Float(), nullable=False),
    sa.Column('alerted_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_syndicate_alert_unique', 'syndicate_alerts', ['match_id', 'market', 'outcome'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('stripe_customer_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_customer_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('spreads_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('home_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_spreads_match_fetched', 'spreads_snapshots', ['match_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_spreads_snapshots_fetched_at'), 'spreads_snapshots', ['fetched_at'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('stripe_subscription_id', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('current_period_end', sa.DateTime(), nullable=True),
    sa.Column('cancel_at_period_end', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('stripe_subscription_id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('totals_snapshots',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('line', sa.Float(), nullable=False),
    sa.Column('over_odds', sa.Float(), nullable=True),
    sa.Column('under_odds', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_totals_match_fetched', 'totals_snapshots', ['match_id', 'fetched_at'], unique=False)
    op.create_index(op.f('ix_totals_snapshots_fetched_at'), 'totals_snapshots', ['fetched_at'], unique=False)
    op.drop_index(op.f('idx_matches_commence_time'), table_name='matches')
    op.drop_index(op.f('idx_matches_sport_key'), table_name='matches')
    op.create_index(op.f('ix_matches_commence_time'), 'matches', ['commence_time'], unique=False)
    op.create_index(op.f('ix_matches_sport_key'), 'matches', ['sport_key'], unique=False)
    op.drop_index(op.f('idx_odds_fetched_at'), table_name='odds_snapshots')
    op.create_index(op.f('ix_odds_snapshots_fetched_at'), 'odds_snapshots', ['fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_snapshots_fetched_at'), table_name='odds_snapshots')
    op.create_index(op.f('idx_odds_fetched_at'), 'odds_snapshots', ['fetched_at'], unique=False)
    op.drop_index(op.f('ix_matches_sport_key'), table_name='matches')
    op.drop_index(op.f('ix_matches_commence_time'), table_name='matches')
    op.create_index(op.f('idx_matches_sport_key'), 'matches', ['sport_key'], unique=False)
    op.create_index(op.f('idx_matches_commence_time'), 'matches', ['commence_time'], unique=False)
    op.drop_index(op.f('ix_totals_snapshots_fetched_at'), table_name='totals_snapshots')
    op.drop_index('idx_totals_match_fetched', table_name='totals_snapshots')
    op.drop_table('totals_snapshots')
    op.drop_table('subscriptions')
    op.drop_index(op.f('ix_spreads_snapshots_fetched_at'), table_name='spreads_snapshots')
    op.drop_index('idx_spreads_match_fetched', table_name='spreads_snapshots')
    op.drop_table('spreads_snapshots')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index('idx_syndicate_alert_unique', table_name='syndicate_alerts')
    op.drop_table('syndicate_alerts')
    op.drop_index(op.f('ix_magic_links_token'), table_name='magic_links')
    op.drop_index(op.f('ix_magic_links_email'), table_name='magic_links')
    op.drop_table('magic_links')
    op.drop_index(op.f('ix_email_subscribers_email'), table_name='email_subscribers')
    op.drop_table('email_subscribers')
    # ### end Alembic commands ###
